### ISSUE TITLE
Build out-dir has underscores, action output uses dashes

### ISSUE THREAD

**Issue by aricpeters** [bscotch/igor-build#3]
I was attempting to use this action to distribute my game to App Store Connect.

Everything works out great, but when I try to build my ios binary I'm getting an error that the out-dir doesn't exist and can't be used as the working-directory for my script. I did some debugging, and it appears that the output for out-dir contains dashes, but the actual directory has underscores.

echo out-dir
<img width="711" alt="image" src="https://github.com/user-attachments/assets/93656f1d-f55e-4416-946e-5478f4cb6bf9">

echo contents of the parent directory of out-dir
<img width="731" alt="image" src="https://github.com/user-attachments/assets/f149f692-0d0b-4b70-8aa6-1d5e3aab7995">

**Comment by shichen85** [comment]
@aricpeters Thanks for the issue! It should be addressed v1.0.2. I have moved the v1 tag to that commit, so if you rerun your workflow with the `bscotch/igor-build@v1` tag should addressed the issue.

**Comment by aricpeters** [comment]
Thanks for the quick fix! Much appreciated @shichen85

**Comment by SinfulPhantom** [comment]
@shichen85 - I am facing a similar issue, but it adds a single underscore to the out-dir

`/Users/runner/work/_actions/bscotch/igor-setup/v1/dist/gm-sandbox/gm-temp/To_The Trenches`

**Comment by shichen85** [comment]
> @shichen85 - I am facing a similar issue, but it adds a single underscore to the out-dir
> 
> `/Users/runner/work/_actions/bscotch/igor-setup/v1/dist/gm-sandbox/gm-temp/To_The Trenches`

What is the name of the project? Is it `To The Tranches` verbatim?

**Comment by shichen85** [comment]
> @shichen85 - yes it is.

That is odd... https://github.com/bscotch/igor-build/blob/c53a586d76326cc555ad73cd100fe5bc5b7ba479/dist/index.js#L34418 should have taken care of it and replaced all the spaces with underscores. Can you post the whole error log here?

**Comment by SinfulPhantom** [comment]
> > @shichen85 - yes it is.
> 
> That is odd... https://github.com/bscotch/igor-build/blob/c53a586d76326cc555ad73cd100fe5bc5b7ba479/dist/index.js#L34418 should have taken care of it and replaced all the spaces with underscores. Can you post the whole error log here?

Error: An error occurred trying to start process '/bin/bash' with working directory '/Users/runner/work/_actions/bscotch/igor-setup/v1/dist/gm-sandbox/gm-temp/To_The Trenches'. No such file or directory
